/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemmonitoringsystem;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.sql.*;
import javax.swing.*;
import java.io.*;
import javax.swing.table.DefaultTableModel;
import java.net.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Vikas
 */
public class Main extends javax.swing.JFrame {
 
       
    private javax.swing.JTextArea txtMainString;
      public static String s1;
    JLabel img;
    public String mainString;
    public static String sendMessage;
    int cnt = 0;
    public static int j = 0;
     Statement st1;
	ResultSet rs1;
	PreparedStatement pst1;
        Connection conn;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel40 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtUsablSpace1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtTotSpace1 = new javax.swing.JTextField();
        txtFreeSpace1 = new javax.swing.JTextField();
        txtFileSysName2 = new javax.swing.JTextField();
        txtFileSysName1 = new javax.swing.JTextField();
        txtUsablSpace2 = new javax.swing.JTextField();
        txtFreeSpace2 = new javax.swing.JTextField();
        txtTotSpace2 = new javax.swing.JTextField();
        txtFileSysName3 = new javax.swing.JTextField();
        txtUsablSpace4 = new javax.swing.JTextField();
        txtFreeSpace4 = new javax.swing.JTextField();
        txtUsablSpace3 = new javax.swing.JTextField();
        txtFreeSpace3 = new javax.swing.JTextField();
        txtTotSpace4 = new javax.swing.JTextField();
        txtTotSpace3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtFileSysName4 = new javax.swing.JTextField();
        txtFileSysName5 = new javax.swing.JTextField();
        txtTotSpace5 = new javax.swing.JTextField();
        txtFreeSpace5 = new javax.swing.JTextField();
        txtUsablSpace5 = new javax.swing.JTextField();
        txtFileSysName6 = new javax.swing.JTextField();
        txtTotSpace6 = new javax.swing.JTextField();
        txtFreeSpace6 = new javax.swing.JTextField();
        txtUsablSpace6 = new javax.swing.JTextField();
        txtFileSysName7 = new javax.swing.JTextField();
        txtTotSpace7 = new javax.swing.JTextField();
        txtFreeSpace7 = new javax.swing.JTextField();
        txtUsablSpace7 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtComputerName = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        txtxOSName = new javax.swing.JTextField();
        txtOSversion = new javax.swing.JTextField();
        txtOSType = new javax.swing.JTextField();
        txtAvlblProcess = new javax.swing.JTextField();
        txtProcesrname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vikas\\Desktop\\p1.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Aparajita", 1, 36)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 102));
        setPreferredSize(new java.awt.Dimension(1800, 1134));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 102));
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1500, 2528));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));

        txtUsablSpace1.setEditable(false);
        txtUsablSpace1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUsablSpace1.setName("txtUsablSpace1"); // NOI18N
        txtUsablSpace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsablSpace1ActionPerformed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(0, 102, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 153));
        jLabel24.setText("File System Name");

        txtTotSpace1.setEditable(false);
        txtTotSpace1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTotSpace1.setName("txtTotSpace1"); // NOI18N
        txtTotSpace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotSpace1ActionPerformed(evt);
            }
        });

        txtFreeSpace1.setEditable(false);
        txtFreeSpace1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFreeSpace1.setName("txtFreeSpace"); // NOI18N
        txtFreeSpace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFreeSpace1ActionPerformed(evt);
            }
        });

        txtFileSysName2.setEditable(false);
        txtFileSysName2.setName("txtFileSysName2"); // NOI18N
        txtFileSysName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileSysName2ActionPerformed(evt);
            }
        });

        txtFileSysName1.setEditable(false);
        txtFileSysName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFileSysName1.setName("txtFileSysName1"); // NOI18N
        txtFileSysName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileSysName1ActionPerformed(evt);
            }
        });

        txtUsablSpace2.setEditable(false);
        txtUsablSpace2.setName("txtUsablSpace2"); // NOI18N
        txtUsablSpace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsablSpace2ActionPerformed(evt);
            }
        });

        txtFreeSpace2.setEditable(false);
        txtFreeSpace2.setName("txtFreeSpace2"); // NOI18N
        txtFreeSpace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFreeSpace2ActionPerformed(evt);
            }
        });

        txtTotSpace2.setEditable(false);
        txtTotSpace2.setName("txtTotSpace2"); // NOI18N
        txtTotSpace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotSpace2ActionPerformed(evt);
            }
        });

        txtFileSysName3.setEditable(false);
        txtFileSysName3.setName("txtFileSysName3"); // NOI18N
        txtFileSysName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileSysName3ActionPerformed(evt);
            }
        });

        txtUsablSpace4.setEditable(false);
        txtUsablSpace4.setName("txtUsablSpace4"); // NOI18N
        txtUsablSpace4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsablSpace4ActionPerformed(evt);
            }
        });

        txtFreeSpace4.setEditable(false);
        txtFreeSpace4.setName("txtFreeSpace4"); // NOI18N
        txtFreeSpace4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFreeSpace4ActionPerformed(evt);
            }
        });

        txtUsablSpace3.setEditable(false);
        txtUsablSpace3.setName("txtUsablSpace3"); // NOI18N
        txtUsablSpace3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsablSpace3ActionPerformed(evt);
            }
        });

        txtFreeSpace3.setEditable(false);
        txtFreeSpace3.setName("txtFreeSpace3"); // NOI18N
        txtFreeSpace3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFreeSpace3ActionPerformed(evt);
            }
        });

        txtTotSpace4.setEditable(false);
        txtTotSpace4.setName("txtTotSpace4"); // NOI18N
        txtTotSpace4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotSpace4ActionPerformed(evt);
            }
        });

        txtTotSpace3.setEditable(false);
        txtTotSpace3.setName("txtTotSpace3"); // NOI18N
        txtTotSpace3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotSpace3ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 153));
        jLabel25.setText("Total Space");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 153));
        jLabel26.setText("Free Space");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 153));
        jLabel27.setText("Usable Space");

        txtFileSysName4.setEditable(false);
        txtFileSysName4.setName("txtFileSysName4"); // NOI18N
        txtFileSysName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileSysName4ActionPerformed(evt);
            }
        });

        txtFileSysName5.setEditable(false);
        txtFileSysName5.setName("txtFileSysName4"); // NOI18N
        txtFileSysName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileSysName5ActionPerformed(evt);
            }
        });

        txtTotSpace5.setEditable(false);
        txtTotSpace5.setName("txtTotSpace4"); // NOI18N
        txtTotSpace5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotSpace5ActionPerformed(evt);
            }
        });

        txtFreeSpace5.setEditable(false);
        txtFreeSpace5.setName("txtFreeSpace4"); // NOI18N
        txtFreeSpace5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFreeSpace5ActionPerformed(evt);
            }
        });

        txtUsablSpace5.setEditable(false);
        txtUsablSpace5.setName("txtUsablSpace4"); // NOI18N
        txtUsablSpace5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsablSpace5ActionPerformed(evt);
            }
        });

        txtFileSysName6.setEditable(false);
        txtFileSysName6.setName("txtFileSysName4"); // NOI18N
        txtFileSysName6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileSysName6ActionPerformed(evt);
            }
        });

        txtTotSpace6.setEditable(false);
        txtTotSpace6.setName("txtTotSpace4"); // NOI18N
        txtTotSpace6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotSpace6ActionPerformed(evt);
            }
        });

        txtFreeSpace6.setEditable(false);
        txtFreeSpace6.setName("txtFreeSpace4"); // NOI18N
        txtFreeSpace6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFreeSpace6ActionPerformed(evt);
            }
        });

        txtUsablSpace6.setEditable(false);
        txtUsablSpace6.setName("txtUsablSpace4"); // NOI18N
        txtUsablSpace6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsablSpace6ActionPerformed(evt);
            }
        });

        txtFileSysName7.setEditable(false);
        txtFileSysName7.setName("txtFileSysName4"); // NOI18N
        txtFileSysName7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileSysName7ActionPerformed(evt);
            }
        });

        txtTotSpace7.setEditable(false);
        txtTotSpace7.setName("txtTotSpace4"); // NOI18N
        txtTotSpace7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotSpace7ActionPerformed(evt);
            }
        });

        txtFreeSpace7.setEditable(false);
        txtFreeSpace7.setName("txtFreeSpace4"); // NOI18N
        txtFreeSpace7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFreeSpace7ActionPerformed(evt);
            }
        });

        txtUsablSpace7.setEditable(false);
        txtUsablSpace7.setName("txtUsablSpace4"); // NOI18N
        txtUsablSpace7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsablSpace7ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 255, 0));

        jLabel17.setBackground(new java.awt.Color(255, 255, 102));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 0));
        jLabel17.setText("Hard Disk Information");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Get Information");
        jButton1.setName("btnGetInfo"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txtFileSysName1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileSysName2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileSysName3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileSysName5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileSysName6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileSysName7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileSysName4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotSpace2)
                    .addComponent(txtTotSpace7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotSpace6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotSpace4)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtTotSpace1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotSpace3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotSpace5, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel26)
                        .addComponent(txtFreeSpace1)
                        .addComponent(txtFreeSpace2)
                        .addComponent(txtFreeSpace3)
                        .addComponent(txtFreeSpace4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFreeSpace5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFreeSpace6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFreeSpace7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtUsablSpace7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(txtUsablSpace6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsablSpace5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsablSpace4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsablSpace1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsablSpace2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsablSpace3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(39, 39, 39))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel39)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel17))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFileSysName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsablSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFileSysName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsablSpace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtFileSysName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsablSpace3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFileSysName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsablSpace4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(9, 9, 9)
                                .addComponent(txtTotSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotSpace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(9, 9, 9)
                                .addComponent(txtFreeSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFreeSpace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtTotSpace3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtFreeSpace3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFreeSpace4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotSpace4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFileSysName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotSpace5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFreeSpace5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsablSpace5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFileSysName6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotSpace6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFreeSpace6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsablSpace6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFileSysName7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotSpace7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFreeSpace7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsablSpace7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("OS Name");

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField11.setName("txtProcesrArch"); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Available Processors");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("Processor Architecture");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("OS Version");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Processor Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Computer Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("OS Type");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("IP Address");

        txtComputerName.setEditable(false);
        txtComputerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtComputerName.setName("txtComputerName"); // NOI18N

        txtIPAddress.setEditable(false);
        txtIPAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIPAddress.setName("txtIPAddress"); // NOI18N
        txtIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddressActionPerformed(evt);
            }
        });

        txtxOSName.setEditable(false);
        txtxOSName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtxOSName.setName("txtxOSName"); // NOI18N
        txtxOSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxOSNameActionPerformed(evt);
            }
        });

        txtOSversion.setEditable(false);
        txtOSversion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOSversion.setName("txtOSversion"); // NOI18N
        txtOSversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOSversionActionPerformed(evt);
            }
        });

        txtOSType.setEditable(false);
        txtOSType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOSType.setName("txtOSType"); // NOI18N
        txtOSType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOSTypeActionPerformed(evt);
            }
        });

        txtAvlblProcess.setEditable(false);
        txtAvlblProcess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAvlblProcess.setName("txtAvlblProcess"); // NOI18N
        txtAvlblProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvlblProcessActionPerformed(evt);
            }
        });

        txtProcesrname.setEditable(false);
        txtProcesrname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtProcesrname.setName("txtProcesrname"); // NOI18N
        txtProcesrname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcesrnameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 51));

        jLabel16.setBackground(new java.awt.Color(255, 255, 102));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 255, 51));
        jLabel16.setText("Your Pc's Hardware & OS Information");

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vikas\\Desktop\\p1.png")); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAvlblProcess, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProcesrname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOSversion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOSType, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtxOSName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIPAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComputerName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtComputerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtxOSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOSType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOSversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcesrname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvlblProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(236, 236, 236))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel37.setBackground(new java.awt.Color(255, 255, 102));
        jLabel37.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 204, 0));

        jLabel38.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 204, 0));
        jLabel38.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(548, 548, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("System Configuration", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        jPanel4.setAutoscrolls(true);
        jPanel4.setPreferredSize(new java.awt.Dimension(1173, 675));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username ", "Operation Performed", " Date  Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.setPreferredSize(new java.awt.Dimension(250, 2050));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("View Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 51));
        jLabel1.setText("Welcome In Tracking Hardware");

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vikas\\Desktop\\p1.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(647, 647, 647)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(880, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel21))
                .addGap(0, 0, 0))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jlabel1");

        jTabbedPane1.addTab("Tracking Hardware", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jButton4.setText("View Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 51));
        jLabel9.setText("Welcome in Tracking Software Details");

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username ", "Software Started & Ended ", " Date  Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setOpaque(false);
        jTable2.setPreferredSize(new java.awt.Dimension(250, 20050));
        jScrollPane2.setViewportView(jTable2);

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vikas\\Desktop\\p1.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(0, 867, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jLabel32))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tracking software Details", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));

        jButton5.setText("View Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 255, 0));
        jLabel28.setText("CPU Load & Process Details");

        jTable5.setAutoCreateRowSorter(true);
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User name", "CPU Load", "Free Memory Space", "Process Name", "Process Load", "Process Memory"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable5.setOpaque(false);
        jTable5.setPreferredSize(new java.awt.Dimension(250, 2050));
        jScrollPane5.setViewportView(jTable5);

        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vikas\\Desktop\\p1.png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(jLabel28))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(2003, 2003, 2003))
            .addComponent(jLabel41)
        );

        jTabbedPane1.addTab("CPU Process Details", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 255, 0));
        jLabel29.setText("Developers");

        jLabel30.setBackground(new java.awt.Color(153, 0, 153));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 0, 153));
        jLabel30.setText("Mr. Vikas R. Desale  ");

        jLabel31.setBackground(new java.awt.Color(102, 255, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 153));
        jLabel31.setText("Mr. Shailendra Kirtikar");

        jLabel23.setBackground(new java.awt.Color(255, 255, 102));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 153));
        jLabel23.setText("E.No.:-BE14S05F005");

        jLabel33.setBackground(new java.awt.Color(255, 255, 102));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 153));
        jLabel33.setText("E. No.:-BE14S05F008");

        jLabel34.setBackground(new java.awt.Color(255, 255, 102));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 153, 51));
        jLabel34.setText("Subject :-Database Management System");

        jLabel35.setBackground(new java.awt.Color(255, 255, 102));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 255, 153));
        jLabel35.setText("Under the Guidance of");

        jLabel36.setBackground(new java.awt.Color(255, 255, 102));
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 153, 204));
        jLabel36.setText("Miss. Karishma Mam");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("(Front-End Developer)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 255));
        jLabel19.setText("(Back-End Develper)");

        jLabel43.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vikas\\Desktop\\p1.png")); // NOI18N

        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vikas\\Desktop\\p1.png")); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel44)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel23)
                            .addComponent(jLabel11))
                        .addGap(168, 168, 168)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel34))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel29)))
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel23))
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(110, 110, 110)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("About Us", null, jPanel7, "");

        jLabel13.setBackground(new java.awt.Color(255, 255, 102));
        jLabel13.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vikas\\Desktop\\dfdfd.png")); // NOI18N
        jLabel13.setText("System Monitoring Software");
        jLabel13.setIconTextGap(20);
        jLabel13.setOpaque(true);
        jLabel13.setPreferredSize(new java.awt.Dimension(120, 120));

        jLabel14.setBackground(new java.awt.Color(255, 255, 102));
        jLabel14.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 204));
        jLabel14.setText("Department of Computer Science And Engineering");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel14.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(255, 255, 102));
        jLabel15.setFont(new java.awt.Font("Algerian", 1, 42)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("     Government College Of Engineering, Aurangabad");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), java.awt.Color.lightGray, java.awt.Color.red));
        jLabel15.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 DefaultTableModel dfm=(DefaultTableModel) jTable1.getModel();
       ((DefaultTableModel)jTable1.getModel()).setNumRows(0);
         jTable1.setModel(dfm);
            
                try
                {  
                     Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/system_monitor","root","root");
                String query = "select * from hardware_monitor";

                if (conn!=null)
                {
                    Statement stmt = conn.createStatement();
                    ResultSet rs;
                    rs= stmt.executeQuery(query);

                    while(rs.next())
                    {
                        Vector v=new Vector();
                    v.addElement(rs.getString(1));
                    v.addElement(rs.getString(2));
                    v.addElement(rs.getString(3));
                    dfm.addRow(v);
                    }

                } 
                }catch(Exception e){}        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        InetAddress ip;
        try {
            //img = new JLabel("Hello", new ImageIcon("d://image/bg.jpg"), JLabel.RIGHT);
            //add(img);
            //img.setBounds(50, 700, 200, 200);
            ip = InetAddress.getLocalHost();
            //System.out.println("Current host name : " + ip.getHostName());
            txtComputerName.setText(ip.getHostName());

            //System.out.println("Current IP address : " + ip.getHostAddress());
            txtIPAddress.setText(ip.getHostAddress());

            String nameOS = System.getProperty("os.name");
            //System.out.println("Operating system Name=>"+ nameOS);
            txtxOSName.setText(nameOS);

            String osType = System.getProperty("os.arch");
            //System.out.println("Operating system type =>"+ osType);
            txtOSType.setText(osType);

            String osVersion = System.getProperty("os.version");
            //System.out.println("Operating system version =>"+ osVersion);
            txtOSversion.setText(osVersion);

            //System.out.println(System.getenv("PROCESSOR_IDENTIFIER"));
            txtProcesrname.setText(System.getenv("PROCESSOR_IDENTIFIER"));

            //System.out.println(System.getenv("PROCESSOR_ARCHITECTURE"));
            txtAvlblProcess.setText("" + Runtime.getRuntime().availableProcessors());

            jTextField11.setText(System.getenv("PROCESSOR_ARCHITECTURE"));

            System.out.println("Free memory (bytes): "
                + Runtime.getRuntime().freeMemory());

            /*
            * This will return Long.MAX_VALUE if there is no preset limit
            */
            long maxMemory = Runtime.getRuntime().maxMemory();
            /*
            * Maximum amount of memory the JVM will attempt to use
            */
            System.out.println("Maximum memory (bytes): "
                + (maxMemory == Long.MAX_VALUE ? "no limit" : maxMemory));

            /*
            * Total memory currently in use by the JVM
            */
            System.out.println("Total memory (bytes): "
                + Runtime.getRuntime().totalMemory());

            NetworkInterface network = NetworkInterface.getByInetAddress(ip);

            byte[] mac = network.getHardwareAddress();

            //System.out.print("Current MAC address : ");

            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < mac.length; i++) {
                sb.append(String.format("%02X%s", mac[i], (i < mac.length - 1) ? "-" : ""));
            }
            // JOptionPane.showMessageDialog(null, mac);
            //System.out.println(sb.toString());
         //   txtMACAdd.setText("" + sb.toString());
        } catch (UnknownHostException e) {
        } catch (SocketException e) {
        } catch (Exception e) {
        }

        //mainString = String.format(txtMACAdd.getText() + ",," + txtIPAddress.getText() + ",," + txtComputerName.getText() + ",," + txtxOSName.getText() + ",," + txtOSType.getText() + ",," + txtOSversion.getText() + ",," + txtProcesrname.getText() + ",," + txtAvlblProcess.getText() + ",," + jTextField11.getText());

        long maxMemory = Runtime.getRuntime().maxMemory();

        File[] roots = File.listRoots();

        /*
        * For each filesystem root, print some info
        */
        String compName = String.format("My Computer Name is .... \t\n" + txtComputerName.getText());

        try {

            File file = new File("C:\\sample.txt");
            FileWriter fw = new FileWriter(file);

            fw.write(compName);
            fw.write("\n" + "vikas");
            fw.close();
        } catch (IOException e) {
        }

        int i = 0;
        for (File root : roots) {
            i = i + 1;

            if (i == 1) {

                System.out.println();
                txtFileSysName1.setText(root.getAbsolutePath());
                txtTotSpace1.setText("" + (int) (root.getTotalSpace() / 1073741824) + " GB");
                txtFreeSpace1.setText("" + (int) (root.getFreeSpace() / 1073741824) + " GB");
                txtUsablSpace1.setText("" + (int) ((root.getTotalSpace()-root.getFreeSpace()) / 1073741824) + " GB");
            }

            if (i == 2) {
                txtFileSysName2.setText(root.getAbsolutePath());
                txtTotSpace2.setText("" + (int) (root.getTotalSpace() / 1073741824) + " GB");
                txtFreeSpace2.setText("" + (int) (root.getFreeSpace() / 1073741824) + " GB");
                txtUsablSpace2.setText("" + (int) ((root.getTotalSpace()-root.getFreeSpace()) / 1073741824) + " GB");
            }
            if (i == 3) {
                txtFileSysName3.setText(root.getAbsolutePath());
                txtTotSpace3.setText("" + (int) (root.getTotalSpace() / 1073741824) + " GB");
                txtFreeSpace3.setText("" + (int) (root.getFreeSpace() / 1073741824) + " GB");
                txtUsablSpace3.setText("" + (int) ((root.getTotalSpace()-root.getFreeSpace()) / 1073741824) + " GB");
            }

            if (i == 4) {
                txtFileSysName4.setText(root.getAbsolutePath());
                txtTotSpace4.setText("" + (int) (root.getTotalSpace() / 1073741824) + " GB");
                txtFreeSpace4.setText("" + (int) (root.getFreeSpace() / 1073741824) + " GB");
                txtUsablSpace4.setText("" + (int) ((root.getTotalSpace()-root.getFreeSpace()) / 1073741824) + " GB");
            }
            if (i == 5) {
                txtFileSysName5.setText(root.getAbsolutePath());
                txtTotSpace5.setText("" + (int) (root.getTotalSpace() / 1073741824) + " GB");
                txtFreeSpace5.setText("" + (int) (root.getFreeSpace() / 1073741824) + " GB");
                txtUsablSpace5.setText("" + (int) ((root.getTotalSpace()-root.getFreeSpace()) / 1073741824) + " GB");
            }
            if (i == 6) {
                txtFileSysName6.setText(root.getAbsolutePath());
                txtTotSpace6.setText("" + (int) (root.getTotalSpace() / 1073741824) + " GB");
                txtFreeSpace6.setText("" + (int) (root.getFreeSpace() / 1073741824) + " GB");
                txtUsablSpace6.setText("" + (int) ((root.getTotalSpace()-root.getFreeSpace()) / 1073741824) + " GB");
            }
            if (i == 7) {
                txtFileSysName7.setText(root.getAbsolutePath());
                txtTotSpace7.setText("" + (int) (root.getTotalSpace() / 1073741824) + " GB");
                txtFreeSpace7.setText("" + (int) (root.getFreeSpace() / 1073741824) + " GB");
                txtUsablSpace7.setText("" + (int) ((root.getTotalSpace()-root.getFreeSpace()) / 1073741824) + " GB");
            }
            if (i == 7) {
                txtFileSysName7.setText(root.getAbsolutePath());
                txtTotSpace7.setText("" + (int) (root.getTotalSpace() / 1073741824) + " GB");
                txtFreeSpace7.setText("" + (int) (root.getFreeSpace() / 1073741824) + " GB");
                txtUsablSpace7.setText("" + (int) ((root.getTotalSpace()-root.getFreeSpace()) / 1073741824) + " GB");
            }

        }

        String d1, d2, d3, d4;

        txtMainString.setText(mainString);
        txtMainString.append(",," + txtFileSysName1.getText());
        txtMainString.append(",," + txtTotSpace1.getText());
        txtMainString.append(",," + txtFreeSpace1.getText());
        txtMainString.append(",," + txtUsablSpace1.getText());

        txtMainString.append(",," + txtFileSysName2.getText());
        txtMainString.append(",," + txtTotSpace2.getText());
        txtMainString.append(",," + txtFreeSpace2.getText());
        txtMainString.append(",," + txtUsablSpace2.getText());

        txtMainString.append(",," + txtFileSysName3.getText());
        txtMainString.append(",," + txtTotSpace3.getText());
        txtMainString.append(",," + txtFreeSpace3.getText());
        txtMainString.append(",," + txtUsablSpace3.getText());

        txtMainString.append(",," + txtFileSysName4.getText());
        txtMainString.append(",," + txtTotSpace4.getText());
        txtMainString.append(",," + txtFreeSpace4.getText());
        txtMainString.append(",," + txtUsablSpace4.getText());

        txtMainString.append(",," + txtFileSysName5.getText());
        txtMainString.append(",," + txtTotSpace5.getText());
        txtMainString.append(",," + txtFreeSpace5.getText());
        txtMainString.append(",," + txtUsablSpace5.getText());

        txtMainString.append(",," + txtFileSysName6.getText());
        txtMainString.append(",," + txtTotSpace6.getText());
        txtMainString.append(",," + txtFreeSpace6.getText());
        txtMainString.append(",," + txtUsablSpace6.getText());

        txtMainString.append(",," + txtFileSysName7.getText());
        txtMainString.append(",," + txtTotSpace7.getText());
        txtMainString.append(",," + txtFreeSpace7.getText());
        txtMainString.append(",," + txtUsablSpace7.getText());

        s1 = txtMainString.getText();
        System.out.println(s1);
        //frame1.add(new jLabel8(new ImageIcon("C:\Users\lenovo\Desktop\computer-04"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsablSpace7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsablSpace7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsablSpace7ActionPerformed

    private void txtFreeSpace7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFreeSpace7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFreeSpace7ActionPerformed

    private void txtTotSpace7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotSpace7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotSpace7ActionPerformed

    private void txtFileSysName7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileSysName7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileSysName7ActionPerformed

    private void txtUsablSpace6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsablSpace6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsablSpace6ActionPerformed

    private void txtFreeSpace6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFreeSpace6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFreeSpace6ActionPerformed

    private void txtTotSpace6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotSpace6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotSpace6ActionPerformed

    private void txtFileSysName6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileSysName6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileSysName6ActionPerformed

    private void txtUsablSpace5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsablSpace5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsablSpace5ActionPerformed

    private void txtFreeSpace5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFreeSpace5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFreeSpace5ActionPerformed

    private void txtTotSpace5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotSpace5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotSpace5ActionPerformed

    private void txtFileSysName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileSysName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileSysName5ActionPerformed

    private void txtFileSysName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileSysName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileSysName4ActionPerformed

    private void txtTotSpace3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotSpace3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotSpace3ActionPerformed

    private void txtTotSpace4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotSpace4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotSpace4ActionPerformed

    private void txtFreeSpace3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFreeSpace3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFreeSpace3ActionPerformed

    private void txtUsablSpace3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsablSpace3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsablSpace3ActionPerformed

    private void txtFreeSpace4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFreeSpace4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFreeSpace4ActionPerformed

    private void txtUsablSpace4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsablSpace4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsablSpace4ActionPerformed

    private void txtFileSysName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileSysName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileSysName3ActionPerformed

    private void txtTotSpace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotSpace2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotSpace2ActionPerformed

    private void txtFreeSpace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFreeSpace2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFreeSpace2ActionPerformed

    private void txtUsablSpace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsablSpace2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsablSpace2ActionPerformed

    private void txtFileSysName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileSysName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileSysName1ActionPerformed

    private void txtFileSysName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileSysName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileSysName2ActionPerformed

    private void txtFreeSpace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFreeSpace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFreeSpace1ActionPerformed

    private void txtTotSpace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotSpace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotSpace1ActionPerformed

    private void txtUsablSpace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsablSpace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsablSpace1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void txtIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddressActionPerformed

    private void txtxOSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxOSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxOSNameActionPerformed

    private void txtOSversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOSversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOSversionActionPerformed

    private void txtOSTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOSTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOSTypeActionPerformed

    private void txtAvlblProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvlblProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvlblProcessActionPerformed

    private void txtProcesrnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcesrnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcesrnameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            // TODO add your handling code here:
         DefaultTableModel dfm=(DefaultTableModel) jTable2.getModel();
       ((DefaultTableModel)jTable2.getModel()).setNumRows(0);
         jTable2.setModel(dfm);
         
                try
                {  
                   Class.forName("com.mysql.jdbc.Driver");
       
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/system_monitor","root","root");
                String query = "select * from software_details";

                if (conn!=null)
                {
                    Statement stmt = conn.createStatement();
                    ResultSet rs;
                    rs= stmt.executeQuery(query);

                    while(rs.next())
                    {
                        Vector v=new Vector();
                    v.addElement(rs.getString(1));
                    v.addElement(rs.getString(2));
                    v.addElement(rs.getString(3));
                    dfm.addRow(v);
                    }

                } 
                }catch(Exception e){}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dfm=(DefaultTableModel) jTable2.getModel();
       ((DefaultTableModel)jTable2.getModel()).setNumRows(0);
         jTable2.setModel(dfm);
         
                try
                {  
                   Class.forName("com.mysql.jdbc.Driver");
       
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/system_monitor","root","root");
                String query = "select * from load_details";

                if (conn!=null)
                {
                    Statement stmt = conn.createStatement();
                    ResultSet rs;
                    rs= stmt.executeQuery(query);

                    while(rs.next())
                    {
                        Vector v=new Vector();
                    v.addElement(rs.getString(1));
                    v.addElement(rs.getString(2));
                    v.addElement(rs.getString(3));
                    v.addElement(rs.getString(4));
                    v.addElement(rs.getString(5));
                    v.addElement(rs.getString(6));
                    dfm.addRow(v);
                    }

                } 
                }catch(Exception e){}
    
    }//GEN-LAST:event_jButton5ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Main().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField txtAvlblProcess;
    private javax.swing.JTextField txtComputerName;
    private javax.swing.JTextField txtFileSysName1;
    private javax.swing.JTextField txtFileSysName2;
    private javax.swing.JTextField txtFileSysName3;
    private javax.swing.JTextField txtFileSysName4;
    private javax.swing.JTextField txtFileSysName5;
    private javax.swing.JTextField txtFileSysName6;
    private javax.swing.JTextField txtFileSysName7;
    private javax.swing.JTextField txtFreeSpace1;
    private javax.swing.JTextField txtFreeSpace2;
    private javax.swing.JTextField txtFreeSpace3;
    private javax.swing.JTextField txtFreeSpace4;
    private javax.swing.JTextField txtFreeSpace5;
    private javax.swing.JTextField txtFreeSpace6;
    private javax.swing.JTextField txtFreeSpace7;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtOSType;
    private javax.swing.JTextField txtOSversion;
    private javax.swing.JTextField txtProcesrname;
    private javax.swing.JTextField txtTotSpace1;
    private javax.swing.JTextField txtTotSpace2;
    private javax.swing.JTextField txtTotSpace3;
    private javax.swing.JTextField txtTotSpace4;
    private javax.swing.JTextField txtTotSpace5;
    private javax.swing.JTextField txtTotSpace6;
    private javax.swing.JTextField txtTotSpace7;
    private javax.swing.JTextField txtUsablSpace1;
    private javax.swing.JTextField txtUsablSpace2;
    private javax.swing.JTextField txtUsablSpace3;
    private javax.swing.JTextField txtUsablSpace4;
    private javax.swing.JTextField txtUsablSpace5;
    private javax.swing.JTextField txtUsablSpace6;
    private javax.swing.JTextField txtUsablSpace7;
    private javax.swing.JTextField txtxOSName;
    // End of variables declaration//GEN-END:variables
}
